### ISSUE TITLE
Décoder les html entities dans les titres des articles

### ISSUE THREAD

**Issue by Ka-Mira** [andritiana/stkNationaly#111]
Certains articles ont des html entities, ex : 
- Emission « Parole de vie quotidienne » &#8211; Radio Anjomara
- Golden Book STK FATSATS : Commandez votre livre d&rsquo;or !

Il y en également dans le texte de l’article, mais comme nous utilisons l’attribut [innerHTML] d’angular, les html entities sont [automatiquement décodées](https://stackoverflow.com/a/58136012) :

<div [innerHTML]="actuality.text"></div>

Cependant, nous utilisons un <h5> pour afficher les titres. Il faudrait rajouter un decode html entities.

**Comment by haryratsimba** [comment]
Création d'un pipe custom dans lequel on utilise la librairie officielle qu'utilise Wordpress dans son éditeur de block Gutenberg pour décoder les HTML entities.
- https://developer.wordpress.org/block-editor/reference-guides/packages/packages-html-entities/
- https://github.com/WordPress/gutenberg/tree/trunk/packages/html-entities
