### ISSUE TITLE
[PROFIL] Regrouper les infos d'un évènement

### ISSUE THREAD

**Issue by hearoy** [andritiana/stkNationaly#143]
Chaque évènement est lié à une catégorie Wordpress, on affiche directement le contenu de l'article avec les titres affichés dans la barre d'onglet au dessus.

https://www.figma.com/file/yarfMJixtMFWU1tHZjZ1td/RNSTK?type=design&node-id=0-1&t=dxV8yPafLASvqK4w-0

[Mon profil]: https://github.com/andritiana/stkNationaly/assets/63500475/4cf0543b-a3fb-4b92-94f4-0877225c69c8
[Mon évènement]: https://github.com/andritiana/stkNationaly/assets/63500475/cb885218-5b93-4ac2-bcaa-3fe6b352b926
[Mes évènements]: https://github.com/andritiana/stkNationaly/assets/63500475/d4bb5960-58cc-49fc-977f-14be453f7a74

| description | maquette |
| ------- | ------- |
| Tuile mes évènements | ![Mon profil][] |
| nouvel endpoint, liste des évènements (start, end, name) | ![Mes évènements][] |
| carousel d'articles, navigable par swipe, les onglets affichent l'article en cours et ceux autour | ![Mon évènement][] |

**Comment by haryratsimba** [comment]
Hello @hearoy 

les changements côté API ont été faits.

Tu trouveras le résumé ici : https://github.com/fpma-stk/stk-national-api-v2/issues/22#issuecomment-1560134240

Pour l'envoi du data tags, il y a une propriété en plus dans la réponse du profil donc pas besoin de faire une requête HTTP en plus.
Pour la récupération des infos de l'évènement, c'est la même requête existante que pour la récup des badges. Il y a une nouvelle propriété dans la réponse pour avoir la catégorie Wordpress.

Merci ! Sois beni
