### ISSUE TITLE
[Profil] Bug : le token refresh ne se fait pas

### ISSUE THREAD

**Issue by hearoy** [andritiana/stkNationaly#144]
Quand le auth token est expiré, si on rafraîchit la page et qu'on retourne au profil, le guard ramène à la page de profil alors qu'on a bien un auth token et un refresh token dans indexedDB.

**Comment by haryratsimba** [comment]
J'ai essayé de reproduire le bug, mais je n'y suis arrivé qu'une seule fois. Après, même en attendant que le JWT expire, en sortant de la partie profil, puis en revenant dessus ça me redirige bien vers la page de profil et non pas la login page.
Peut être il y a t'il un scénario particulier pour reproduire ?
