### ISSUE TITLE
PROFIL : maquette d'affichage du profil 

### ISSUE THREAD

**Issue by Ka-Mira** [andritiana/stkNationaly#63]
- Intégration avec le design existant
- Parcours utilisateur global 
- Maquettes affinées, une fois validé avec l'équipe et le BN

**Comment by haryratsimba** [comment]
Composants Ionic : https://ionicframework.com/docs/components

**Comment by hearoy** [comment]
Lien [figma](https://www.figma.com/file/yarfMJixtMFWU1tHZjZ1td/RNSTK) 
Merci @ChloeTR !
