### ISSUE TITLE
BUG : Blank screen lorsque l'on ouvre un android 11/12 en particulier Samsung

### ISSUE THREAD

**Issue by haryratsimba** [andritiana/stkNationaly#86]
Ce problème se produit sur les Android récents > 9, et en particulier les Samsung.

En lançant en debug sur un vrai téléphone, il y a l'erreur suivante : 

```
Could not open database SQLitePlugin
```

D'après les threads suivants, il faut utiliser la version `"cordova-sqlite-storage": "6.0.0"` :
- https://github.com/storesafe/cordova-sqlite-storage/issues/954#issuecomment-1049243363
- https://forum.ionicframework.com/t/sqlite-error-with-ionic-6-and-capacitor-3/223857/3

Pour fixer l'erreur suivante : package android.support.annotation does not exist, il a fallu rajouter `cordova-plugin-androidx-adapter`
- https://stackoverflow.com/a/71318218

J'ai mis à jour les versions d'android également.

**Comment by hearoy** [comment]
fixed by #87
